[dataset]
loader = 'arff'
# Ignored if -t (--train_files) is passed to the CLI.
files = ['examples/files/dataset/online-shoppers.arff']
show_columns = true
plugins = ['examples.files', 'examples.open_ml']

[preprocess]
label = 'Revenue'
y_preprocessors = [
    'label_encoder'
]
# Should label_encode = true be deprecated ?
# label_encode = true

transformers.passthrough = [
  'Informational_Duration',
  'SpecialDay',
  'BounceRates',
]
transformers.one_hot_encoder = ['Weekend', 'Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType']

# The shuffle value is its random_state seed.
preprocessors.shuffle = 1
# Negative values start at the end:
preprocessors.drop_rows = -5
# Dropped samples left out for predictions (relevant for testing the final model),
# file path will be the on specified in training predict_file.
drop_rows_to_predict_file = true

# Pipeline suffixes are removed from columns by default:
verbose_feature_names_out = false

# Multiple files will be combined, by default the "index" axis is used.
# If 'index' axis is used, a group column with the filename will be added.
# If 'column' axis is used, no grouping will occur.
files_axis = 'index'

[eda]
enabled = false
show_plots = true
save_images = false
save_timestamp = true
images_extension = 'png'
images_directory = 'output/eda'
plots = [
  'heatmap',
]
# distribution_x=column_a
figsize = [35, 35]
dpi = 200
# features = ['column a', 'column b', 'column n']

[training]
enabled = true
pipeline = 'imblearn.pipeline'
samplers = [
    'sampler/tomek_links',
]
estimators = [
    'classifier/kneighbors_classifier',
]
runners = [
    'roc_curve',
    'score',
]
scoring = 'f1'

splitting_method.kfold_stratified = 3

save_model = true
model_timestamp = false
models_directory = 'models'
# Use a random seed (default) or specify one
seed = 7368298
# @see https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values

[predictions]
predict_file = 'tests/online-shoppers/predictions/classifier/online-shoppers-predictions.csv'
