[dataset]
loader = 'open_ml'
# Ignored if -t (--train_files) is passed to the CLI.
files = ['HappinessRank_2015']
show_columns = true
plugins = 'examples.open_ml'

[preprocess]
label = 'Happiness Score'
label_encode = false
# The shuffle value is its random_state seed.
preprocessors.shuffle = 1
preprocessors.drop_rows = -5
# Dropped samples left out for predictions (relevant for testing the final model):
drop_rows_to_predict_file = true
transformers.passthrough = [
  'Economy (GDP per Capita)',
  'Family',
  'Health (Life Expectancy)',
  'Freedom',
  'Trust (Government Corruption)',
  'Generosity',
  'Dystopia Residual'
]
transformers.one_hot_encoder = ['Region']
transformers.scaler = ['Standard Error']

# Pipeline suffixes are removed from columns by default:
verbose_feature_names_out = false

# Multiple files will be combined, by default the "index" axis is used.
# If 'index' axis is used, a group column with the filename will be added.
# If 'column' axis is used, no grouping will occur.
files_axis = 'index'

[eda]
enabled = false
show_plots = true
save_images = false
save_timestamp = true
images_extension = 'png'
images_directory = 'output/eda'
plots = [
  'heatmap',
]
# distribution_x=column_a
figsize = [35, 35]
dpi = 200
# features = ['column a', 'column b', 'column n']

[training]
# Disable to do eda only.
enabled = true
pipeline = 'imblearn.pipeline'
estimators = [
    'regressor/xgboost',
    'regressor/lgbm_regressor',
    'regressor/hgbr',
]
runners = [
    'score',
]
scoring = 'r2'

splitting_method.kfold = 5
splitting_method.kfold_shuffle = 5
splitting_random_state = 36572

save_model = true
model_timestamp = false
models_directory = 'models'
# Use a random seed (default) or specify one
seed = 7368298
# @see https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values

[predictions]
enabled = true
loader = 'csv'
preprocess = false
predict_file = 'tests/happiness_rank/test.csv'
# Leave out the models param to use fitted pipelines from the previous training.
models = [
  'models/happiness_rank-regressor/xgboost.pkl',
  'models/happiness_rank-regressor/lgbm_regressor.pkl',
  'models/happiness_rank-regressor/hgbr.pkl'
]
# Available plugins: binary, multiclass, regressor
objective = 'regression'
# Use the preprocess, as in training.
threshold = 0.5
predictions_directory = 'tests/iris/predictions'
save_predictions = true
predictions_timestamp = false
# Keep X data features in the final predictions columns.
keep_data = true


[debug]
enabled = false
port = 5678
host = '127.0.0.1'
wait_for_client = true
